version: '3.9'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit-app:
    build: .
    image: streamlit-app
    container_name: streamlit_container
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
    ports:
      - "8501:8501"
    environment:
      MONGO_URI=mongodb://admin:password@mongodb:27017/
    # command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  mongo_data:
