version: '3.9'

services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gradio-app:
    build: .
    image: gradio-app
    container_name: gradio_container
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
    ports:
      - "7860:7860"

volumes:
  mongo_data:
